### ISSUE TITLE
Add docker-compose examples

### ISSUE THREAD

**Issue by sgaunet** [sgaunet/postgis#1]
* To mount a local dir corresponding to the pgdata
* to mount sql script
...

```
version: '3.7'
services:
  postgres-server:
    image: postgres:15
    ports:
    - 5432:5432
    stop_grace_period: 1m
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=password
    volumes:
    - ./data-postgres:/var/lib/postgresql/data

```
